application: shadowquant
version: 5
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "7d 5h"

handlers:

- url: /static/
  static_dir: static

- url: /favicon\.ico
  static_files: favicon.png
  upload: favicon\.png

- url: .*
  script: main.app

libraries:
- name: django
  version: "1.5"

- name: MySQLdb
  version: "latest"

- name: ssl
  version: "latest"

- name: PIL
  version: "latest"

builtins:
- django_wsgi: on
